server.port=8082

# ===============================
# LOG
# ===============================
logging.level.root=INFO
logging.level.id.co.allobank=DEBUG

# ===============================
# SWAGGER
# ===============================
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.api-docs.enabled=true

springdoc.default-consumes-media-type=application/json
springdoc.default-produces-media-type=application/json

open-api.title=exchangerate
open-api.description=REST API for currency exchange rate aggregation using Frankfurter API, supporting real-time conversion and standardized response format
open-api.version=v1.0.0

# ===============================
# EXTERNAL API
# ===============================
frankfurter.base-url=https://api.frankfurter.app/