spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/employee-java
spring.datasource.username=postgres
spring.datasource.password=Ultraman2!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.error.include-message=always
application.security.jwt.secret-key=1111111111111111111111111111111mysupersecretkeymysupersecretkey123456
application.security.jwt.refresh-token.expiration=86400000
application.security.jwt.expiration=86400000
# Spring Application Configuration

# Server Configuration
server.port=8080

# App Custom Configuration
app.api.base-url=https://api.frankfurter.app
app.api.connection-timeout=5000
app.api.read-timeout=10000
app.github.username=your-github-username

# Logging Configuration
logging.level.com.finance.api=DEBUG
logging.level.org.springframework.web=INFO