spring:
  application:
    name: idr-rate-aggregator

frankfurter:
  base-url: https://api.frankfurter.app/
  historical-range: 2024-01-01..2024-01-05

github:
  username: nurmaya 

logging:
  level:
    org.springframework.web.reactive.function.client: DEBUG