spring.application.name=splitbiller

server.port=4110
app.github-username=killedbydagger

spring.datasource.url=jdbc:mysql://localhost:3306/exchange?useSSL=false
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.hibernate.ddl-auto=update
