spring.application.name=backendtest

# Frankfurter API Configuration
frankfurter.base-url=https://api.frankfurter.app
frankfurter.github-username=hollymolly2708

# Force servlet (Spring MVC)
spring.main.web-application-type=servlet