spring:
  application:
    name: pemilu2024-service
  datasource:
    url: jdbc:h2:tcp://localhost:9092/~/Desktop/h2-db/pemilu2024;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database-platform: org.hibernate.dialect.H2Dialect