app:
  github-username: ${APP_GITHUB_USERNAME:deafultuser}

frankfurter:
  base-url: ${EXTERNAL_API_BASE_URL:https://api.frankfurter.dev/v1}

server:
  port: 8125

spring:
  application:
    admin:
      enabled: true
    name: exchangerate
    config:
      import: optional:file:.env[.properties]
