api.client.baseurl=https://api.frankfurter.app
api.client.connectiontimeout=5000
api.client.readtimeout=5000
spring.datasource.url=jdbc:h2:mem:idrdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.h2.console.enabled=true