spring.application.name=allow

logging.level.com.allobank.idr=DEBUG
logging.level.reactor.netty=INFO
logging.level.org.springframework.web.reactive=DEBUG

frankfurter.base-url=https://api.frankfurter.app


github.username=hafizs08

webclient.timeout-seconds=10

server.port=8080