# Spring Config
spring.application.name=takehometest

# Frankfurter API Configuration
app.frankfurter.baseurl=https://api.frankfurter.dev/v1
app.frankfurter.timeout-ms=5000

# Github Params
app.github.username=irzaardian

# Historical exchange rate configuration
# Used by HistoricalIdrUsdFetcher at startup
app.historical.from-date=2026-01-01
app.historical.to-date=2026-01-05
app.historical.base=IDR
app.historical.target=USD