spring.application.name=allobank-backend-test
server.port=8080

# REST only
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.com.zultest=DEBUG

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1

external.api.frankfurter.base-url=https://api.frankfurter.app
external.api.frankfurter.timeout-connect=5000
external.api.frankfurter.timeout-read=5000
