server:
  port: 8089

spring:
  application:
    name: allo-bank-backend-test

frankfurter:
  api:
    base-url: https://api.frankfurter.app
    timeout: 5000
    headers:
      Accept: application/json

external:
  frankfurter:
    latest-url: "https://api.frankfurter.app/latest?base=IDR"
    currencies-url: "https://api.frankfurter.app/currencies"
    historical-url: "https://api.frankfurter.app/2024-01-01..2024-01-05?from=IDR&to=USD"

resources:
  - latest_idr_rates
  - historical_idr_usd
  - supported_currencies

spread:
  github-username: "tisnandanurhidayat"

logging:
  level:
    root: INFO
    id.tisnanda.allobank: INFO
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"