spring.application.name=exchangerateagregator
server.servlet.context-path=/api
server.port=8080

external.frankfurter.base-url=https://api.frankfurter.app
external.frankfurter.endpoint.latest-idr-rate=/latest
external.frankfurter.endpoint.history=/{dateRange}
external.frankfurter.endpoint.currency=/currencies
